version: '3.4' 
services:
  reverse-proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
      - ./logs:/var/log/nginx/
    ports:
      - 80:80
    networks:
      - app-network
  app:
    # A container that exposes an API to show its IP address
    image: containous/whoami
    networks:
      - app-network
#    scale: 2
  webapp:
    build: ./simple_app
    healthcheck:
      test: curl -f http://localhost:8080/sample || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

