version: '3.4'
services:

  #Tomcat Service
  webapp1:
    build: ./simple_app
    healthcheck:
      test: curl -f http://localhost:8080/sample || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - app-network

  webapp2:
    build: ./simple_app
    healthcheck:
      test: curl -f http://localhost:8080/sample || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - app-network
 
  #Nginx Service

  web:
    image: nginx
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
      - ./logs:/var/log/nginx/
    ports:
      - "80:80"
    environment:
      - APP_NAME1=webapp1
      - APP_NAME2=webapp2
      - NGINX_HOST=172.25.61.57
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/mysite.conf && exec nginx -g 'daemon off;'"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
